on:
  push:
     branches:
       - main

name: 🚀 Build and Deploy

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown and blogdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown"))'

      - name: Install hugo
        run: Rscript -e 'blogdown::install_hugo("0.88.1")'

      - name: Build site with blogdown
        run: |
          setwd('./website/')
          blogdown::build_site()
        shell: Rscript {0}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.



