/* SSA */

var ssa_sf = [
	// "I am usually not much affected by the feeling of clothes on my bare skin.",
	// "I am not easily alarmed.",
	// "My strong emotions in a situation carry over for 1-2 hours after I leave it.",
	// "I am not influenced as much as most people by the weather.",
	// "I am strongly emotionally moved when many things are happening at once.",
	// "Sudden changes are not emotionally moving for me.",
	// "Having heard a sound, I often lay awake at night for some time.",
	// "I don’t get as emotionally moved by intense stimulation, as others.",
	"The mood of a physical setting affects me a lot.",
	// "When I get stirred up, my heart beats fast and keeps on beating for a while.",
	// "I am generally less emotional, both in a positive and negative way, than others.",
	"A sudden strong odour can have a great influence on me.",
	"When I walk into a crowded room, it immediately has a big effect on me.",
	// "Things usually don’t get me stirred up.",
	// "A long spell of bad weather affects me greatly.",
	// "A very emotional incident early in the day can change my mood for the whole day.",
	// "I am not affected much by sudden or intensive events.",
	// "I am not affected much by the hardness or softness of the furniture I use.",
	"Strong foul odours can make me tense.",
	// "Drastic changes in weather can affect my mood.",
	// "I am calm most of the time.",
	// "I am not a person who feels changes in the mood of a situation.",
	"I am tremendously affected by sudden loud noises.",
	// "I get excited easily.",
	// "I am not bothered by the sight of an accident for a long time.",
	// "I sometimes tremble from excitement.",
	// "Strong emotions don’t have a lasting effect on me.",
	"I am not one to be strongly moved by an unusual odour.",
	// "I quickly overcome being alarmed.",
	// "I am excited or move long after a good movie.",
	// "Sometimes if I have many things to do at once, I get overexcited.",
	// "I am not affected much by the feel or textures of the clothes I wear. ",
	"I am excitable in a crowded situation.",
	"It is easy to feel agitated when a lot is happening.",
	// "Highly arousing stimulation affects me for a short time.",
	"I don’t react much to sudden odd sounds.",
	// "Sometimes I get emotionally moved over even simple things.",
	"My moods are not quickly affected when I enter new places.",
	// "Sudden changes have an immediate and large effect on me.",
	// "Extremes in temperatures don’t affect me a great deal."
];